---
# file: staging.yaml

# General setup
domain: admiral0.it
main_user_name: me

# Secondary spam domain
# this is for virtual users
secondary_domain: realfakemails.com

# Ansible stuff
ansible_python_interpreter: /usr/bin/python3
ansible_user: root